name: learn-1
on: [push]
jobs:
  SimpleSample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wxdlong/hello-action@v7
        name: say hello
        with:
          who-to-greet: 'Ethan'
      - run: pwd
        name: where am i
      - run: ls -lart
        name: what is here
      - run: ./scripts/shell1.sh
        name: run script

