name: learn-1
on: [push]
jobs:
  FirstHalf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wxdlong/hello-action@v7
        name: say hello
        with:
          who-to-greet: 'Ethan'
      - run: pwd
        name: where am i
      - run: ls -lart
        name: what is here
      - run: ./scripts/shell1.sh > output.txt
        name: run script
      - name: upload sample artifact
        uses: actions/upload-artifact@v2
        with:
          name: output-artifact
          path: output.txt
  SecondHalf:
    runs-on: ubuntu-latest
    needs: FirstHalf
    steps:
      - name: download sample artifact
        uses: actions/download-artifact@v2
        with:
          name: output-artifact
      - run: ls -lart
        name: what is here
      - run: wc -l output.txt
        name: get line count

